### ISSUE TITLE
Light Switch Exercise in React.js

### ISSUE THREAD

**Issue by fostyler** [AnaStasia2308/my-react-project#1]
**Prepare your code**
1. In your terminal, `cd` to the working directory, `git status`
2. Make sure you are on branch `master`.  If you are not, `git checkout master`
3. If you see changes left over from last week, you can either save them to a separate branch, or throw the changes away.
  - To throw the changes away `git reset --hard`
  - To save your things to a new branch
    A. `git checkout -b some-new-branch`
    B. `git add -A`
    C. `git commit -m 'something I did last week'`
    D. `git push origin some-new-branch`
    E. Switch back to master branch `git checkout master`
4. When you do `git status` now, it should say the working directory is clean
5. Start your server `yarn start`, ensure you can see your application at `http://localhost:3000`
6. Create a `components` directory inside of `src`

**Create a lightbulb component**
1. Inside of `components` directory, create a new directory called `LightBulb`.
2. Inside of this directory, create a new file `index.js` and make a react component there.
3. This react component should accept one prop `lightIsOn`
4. Make this react component return an image, and the src will toggle to on/off image file with `lightIsOn` value changing true or false.

**Create a light switch component**
1. Inside of the `components` directory, create a new directory called `LightSwitch`
2. Inside of this directory, create a new file `index.js` and make a react component there
3. This react component accepts no props.  It has 1 piece of local state `lightIsOn` which can be created with `useState`.  This component must also import the component LightBulb.
4. Return a blob of JSX that includes the <LightBulb /> component, as well as a button.
5. When the button is clicked, it must toggle the state `lightIsOn` from true to false, and vice versa.
7. Local state `lightIsOn` should be passed to the light bulb `<LightBulb lightIsOn={lightIsOn} />`

**Include in App.js**
1. Inside of App.js, import the light switch and include it in the template.
2. Once you have one light bulb working, include two more in to app.js
3. Now you should have 3 LightSwitches, which inludes the button and the LightBulb component.
4. The light switches should all be operating independently of one another.

_Note: You will not see anything in your browser until you include it in App.js.  You can do these steps out of order if you choose._

**Comment by fostyler** [comment]
@AnaStasia2308 Can you please commit and push your work from last week?

- `git add -A`
- `git commit -m 'work from last week'`
- `git push origin [some-new-branch]`

**Comment by AnaStasia2308** [comment]
@fostyler I just committed and submitted a work from last week
